urls = [
    "https://www.team2.travel",
    "https://www.team2.travel/ts-page2",
    "https://www.team2.travel/ts-page3",
    "https://www.team2.travel/ts-page4",
    "https://www.team2.travel/ts-page5",
    "https://www.team2.travel/ts-page6",
    "https://www.team2.travel/ts-page7",
    "https://www.team2.travel/ts-page8",
    "https://www.team2.travel/ts-page9",
    "https://www.team2.travel/ts-page10",
    "https://www.team2.travel/ts-page11",
    "https://www.team2.travel/ts-page12",
    "https://www.team2.travel/ts-page13",
    "https://www.team2.travel/ts-page14",
    "https://www.team2.travel/ts-page15",
]
